### ISSUE TITLE
Renaming componentParent to parentComponent

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#56]
I am thinking of making one backwards incompatible change, but I think it is still early enough to be able to pull it off. I would rename `componentParent` to `parentComponent`. What are thoughts on this by others?

**Comment by rclai** [comment]
Haha, I'm guessing you got bitten again. I was just starting to get used to it. I am okay with renaming.

**Comment by mitar** [comment]
No, I was waiting for somebody else to open a ticket. ;-)

**Comment by mquandalle** [comment]
I also support the renaming, `parentComponent` is much more consistent with DOM names such as `parentElement` or `parentNode`.

I’m not sure how you want to handle this kind of breaking changes. One way to do it would be to deprecate `componentParent` by proxing it to `parentComponent` and adding a `console.warn` message.

**Comment by mitar** [comment]
Yea. Or just hope that we are early enough in the project (no 1.0 release yet) that I can pull this off just by breaking it. :-) Sadly Meteor does not handle versions before 1.0 specially, as it should, and upgrades things automatically. Semver allows breaking changes before 1.0 version. But Meteor just upgrades them. See [here](https://github.com/meteor/meteor/issues/4170#issuecomment-96630972).

Maybe I should introduce history file in the project repository.

**Comment by bensmeets** [comment]
Renaming sounds fine (simple find and replace should fix it), although a small console.warn would be nice.

**Comment by mitar** [comment]
I created history file: https://github.com/peerlibrary/meteor-blaze-components/blob/master/HISTORY.md

**Comment by mitar** [comment]
Hm, I am still not sure if it would be really good to rename it. So `parentComponent`, but keeping `componentChildren`?

**Comment by mitar** [comment]
Especially if we introduce more methods to traverse component tree: #81.

**Comment by mitar** [comment]
Renamed methods:
- `componentChildren` to `childrenComponents`
- `componentChildrenWith` to `childrenComponentsWith`
- `addComponentChild` to `addChildComponent`
- `removeComponentChild` to `removeChildComponent`
- `componentParent` to `parentComponent`
